[project]
name = "forget-me-not"
version = "0.1.0"
description = "A groceries list app"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "debugpy>=1.8.14",
    "flask>=3.1.1",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
]
